services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  spring-app:
    build:
      context: .
      dockerfile: backend\API\Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  react-app:
    build:
      context: .
      dockerfile: \frontend\Dockerfile
    ports:
      - "5173:5173"

volumes:
  mongodb_data:
