version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /path/to/mongodb/data:/data/db
  spring-app:
    build:
      context: .
      dockerfile: backend\API\Dockerfile-spring
    ports:
      - "8080:8080"
  react-app:
    build:
      context: .
      dockerfile: frontend\Dockerfile-react
    ports:
      - "5173:5173"
