export const BackendData = () => [
    { data: { id: 'node1', label: 'Python' } },
    { data: { id: 'node2', label: 'Java' } },
    { data: { id: 'node3', label: 'Node.js' } },
    { data: { id: 'node4', label: 'Django' } },
    { data: { id: 'node5', label: 'Spring Boot' } },
    { data: { id: 'node6', label: 'Express.js' } },
    { data: { id: 'node7', label: 'SQL' } },
    { data: { id: 'node8', label: 'NoSQL' } },
    { data: { id: 'node9', label: 'Docker' } },
    { data: { id: 'node10', label: 'Kubernetes' } },
    { data: { id: 'edge1', source: 'node1', target: 'node4' } },
    { data: { id: 'edge2', source: 'node2', target: 'node5' } },
    { data: { id: 'edge3', source: 'node3', target: 'node6' } },
    { data: { id: 'edge4', source: 'node4', target: 'node7' } },
    { data: { id: 'edge5', source: 'node5', target: 'node7' } },
    { data: { id: 'edge6', source: 'node6', target: 'node8' } },
    { data: { id: 'edge7', source: 'node7', target: 'node9' } },
    { data: { id: 'edge8', source: 'node8', target: 'node9' } },
    { data: { id: 'edge9', source: 'node9', target: 'node10' } },
];