export const roadData = () => [
    { data: { id: 'node1', label: 'HTML' } },
    { data: { id: 'node2', label: 'CSS' } },
    { data: { id: 'node3', label: 'JavaScript' } },
    { data: { id: 'node4', label: 'Node.js' } },
    { data: { id: 'node5', label: 'Express.js' } },
    { data: { id: 'node6', label: 'MongoDB' } },
    { data: { id: 'node7', label: 'React' } },
    { data: { id: 'node8', label: 'Vue.js' } },
    { data: { id: 'node9', label: 'Angular' } },
    { data: { id: 'node10', label: 'TypeScript' } },
    { data: { id: 'node11', label: 'GraphQL' } },
    { data: { id: 'node12', label: 'SQL' } },
    { data: { id: 'node13', label: 'PostgreSQL' } },
    { data: { id: 'node14', label: 'MySQL' } },
    { data: { id: 'node15', label: 'Firebase' } },
    { data: { id: 'node16', label: 'Python' } },
    { data: { id: 'node17', label: 'Django' } },
    { data: { id: 'node18', label: 'Spring Boot' } },
    { data: { id: 'node19', label: 'Java' } },
    { data: { id: 'node20', label: 'C#' } },
    { data: { id: 'edge1', source: 'node1', target: 'node2' } },
    { data: { id: 'edge2', source: 'node2', target: 'node3' } },
    { data: { id: 'edge3', source: 'node3', target: 'node4' } },
    { data: { id: 'edge4', source: 'node4', target: 'node5' } },
    { data: { id: 'edge5', source: 'node5', target: 'node6' } },
    { data: { id: 'edge6', source: 'node3', target: 'node7' } },
    { data: { id: 'edge7', source: 'node3', target: 'node8' } },
    { data: { id: 'edge8', source: 'node3', target: 'node9' } },
    { data: { id: 'edge9', source: 'node3', target: 'node10' } },
    { data: { id: 'edge10', source: 'node3', target: 'node11' } },
    { data: { id: 'edge11', source: 'node3', target: 'node12' } },
    { data: { id: 'edge12', source: 'node12', target: 'node13' } },
    { data: { id: 'edge13', source: 'node12', target: 'node14' } },
    { data: { id: 'edge14', source: 'node5', target: 'node15' } },
    { data: { id: 'edge15', source: 'node16', target: 'node17' } },
    { data: { id: 'edge16', source: 'node17', target: 'node18' } },
    { data: { id: 'edge17', source: 'node19', target: 'node20' } },
]